spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jdbc01?characterEncoding=utf-8&useSSL=true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
  jpa:
    show-sql: true
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: dev
  redis:
    port: 6379
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server:
  port: 8081
